# Generated by Django 4.2.7 on 2024-08-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('some_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='somemodel',
            name='some_field',
            field=models.CharField(default='', max_length=64),
        ),
    ]
