site_name: "PCA: Scenery"
site_url: https://pointcarre-app.github.io/pca-scenery/
repo_url: https://github.com/pointcarre-app/pca-scenery
repo_name: pointcarre-app/pca-scenery

theme:
  name: material
  logo: assets/logo-jules-white.svg
  custom_dir: docs/stylesheets
  palette:
    - scheme: default
      primary: "#6032bc"  
      accent: "#6032bc"  
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: "#6032bc"  
      accent: "#6032bc"  
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css


nav:
  - Home: index.md
  - Installation: installation.md
  - Glossary: glossary.md
  - Usage: usage.md
  - Settings: settings.md
  - Manifest specification: manifest_specification.md
  - API Reference: api.md 
  - Examples: examples/basic.md
  - Contributing: contributing.md
plugins:
  - search
  - mkdocstrings:
      default_handler: python

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true