site_name: Scenery
site_url: https://selimPCA.github.io/pca-scenery/
repo_url: https://github.com/selimPCA/pca-scenery
repo_name: username/repo-name

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Installation: installation.md
  - Glossary: glossary.md
  - Usage: usage.md
  - Settings: settings.md
  - Manifest specification: manifest_specification.md
  - API Reference: api.md 
  - Examples: todo
  - Contributing: contributing.md
plugins:
  - search
  - mkdocstrings:
      default_handler: python

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true