name: Python Checks

on:
  push:
    branches: [master, test]
  pull_request:
    branches: [master, test]

jobs:
  ruff:
    name: Ruff
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false  # Continue with other versions even if one fails
        matrix:
          python-version: ['3.12']
  
    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v5
          with:
            python-version: ${{ matrix.python-version }}
        - run: |
            python -m venv env_test
            source env_test/bin/activate
            python -m pip install --upgrade pip
            pip install .
            pip install -r dev-requirements.txt  
        - run: |
            ruff check rehearsal
            ruff check src 
        - if: always()  # Run even if tests fail
          run: |
            rm -rf env_test
            rm -rf build

  mypy:
    name: Mypy
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false  # Continue with other versions even if one fails
        matrix:
          python-version:  ['3.12']
    
    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v5
          with:
            python-version: ${{ matrix.python-version }}
        - run: |
            python -m venv env_test
            source env_test/bin/activate
            python -m pip install --upgrade pip
            pip install .
            pip install -r dev-requirements.txt  
        - run: |
            mypy rehearsal
            mypy src
        - if: always()  # Run even if tests fail
          run: |
            rm -rf env_test
            rm -rf build